<div class="footer">
	<div class="row">
		<div class="col-md-5">
			
		</div>
		<div class="col-md-2">
			<nav>
				<ul>
					<li><a href="index.php?page=heureux">Heureux</a></li>
					<li><a href="index.php?page=cauchemar">Cauchemar</a></li>
					<li><a href="index.php?page=erotique">Erotique</a></li>
					<li><a href="index.php?page=premonitoire">Prémonitoire</a></li>
					<li><a href="index.php?page=brise">Brisé</a></li>
					<li><a href="index.php?page=eveille">Eveillé</a></li>
					<li><a href="index.php?page=merdique">Merdique</a></li>
				</ul>
			</nav>
		</div>
		<div class="col-md-5">
			
		</div>
	</div>
</div>