<div class="footer">
	<div class="container main">
		<div class="row">
			<div class="col-md-4">
				<nav>
					<li><a href="">Informations</a></li>
					<li><a href="">Promotions</a></li>
					<li><a href="">Nouveaux produits</a></li>
					<li><a href="">Meilleures ventes</a></li>
					<li><a href="">Nos magasins</a></li>
					<li><a href="">Mon compte</a></li>
					<li><a href="">Contactez-nous</a></li>
				</nav>
					<p>Paiement sécurisé. You can pay using :</p>
					<img class="footer_image"src="./images/payer.png" alt="">
			</div>
			<div class="col-md-2 footer_lien">
				<nav>
					<ul>
						<h3>Catégories :</h3>
						<li><a href="index.php?page=heureux">Heureux</a></li>
						<li><a href="index.php?page=cauchemar">Cauchemar</a></li>
						<li><a href="index.php?page=erotique">Erotique</a></li>
						<li><a href="index.php?page=premonitoire">Prémonitoire</a></li>
						<li><a href="index.php?page=brise">Brisé</a></li>
						<li><a href="index.php?page=eveille">Eveillé</a></li>
						<li><a href="index.php?page=merdique">Merdique</a></li>
					</ul>
				</nav>
			</div>
			<div class="col-md-6 flaticon">
				<a href=""><i class="flaticon-facebook2"></i></a>
				<a href=""><i class="flaticon-twitter"></i></a>
				<a href=""><i class="flaticon-google-plus"></i></a>
				<a href=""><i class="flaticon-instagram19"></i></a>
				<a href=""><i class="flaticon-youtube30"></i></a>
			</div>
		</div>
	</div>
</div>