<h2>Bienvenue sur Idream !</h2>
<p>Idream est un site révolutionnaire, il vous vend du rêve !</p>
<p>Notre équipe est la meilleure possible pour vous satisfaire au maximum. Avoir un rêve avec nous n'est plus un soucis, que ce soit de devenir riche, de trouver la femme de votre vie ou encore de se faire poursuivre par un vampire, tout est possible !</p>
<p>Alors n'hésitez pas à profiter de nos excellents produits, car comme l'a dit Martin Luther King : I HAVE A DREAM ! </p>
<p>On vous souhaite une bonne visite sur notre site !</p>