<div class="row">
	<form action="index.php?ajax=panier&edit" class="modif_panier" data-id="<?=$i?>">
		<div class="col-sm-2">
			<a href="index.php?ajax=panier&delete&id_produit=<?=$id_produit?>&duree=<?=$duree?>" class="panier_supp_link">X</a>
			<?=$reference?>
		</div>
		<div class="col-sm-4"><?=$nom_produit?></div>
		<div class="col-sm-1">
			<select name="duree" id="mp_duree<?=$i?>">
				<option value="15" <?=$duree15?>>15 min</option>
				<option value="30" <?=$duree30?>>30 min</option>
				<option value="45" <?=$duree45?>>45 min</option>
				<option value="60" <?=$duree60?>>60 min</option>
			</select>
		</div>
		<div class="col-sm-1 quant_panier"><input type="number" name="quantity" id="mp_quantity<?=$i?>" value="<?=$quantity?>"></div>
		<div class="col-sm-2">Prix unitaire : <br><?=$prix?> €</div>
		<div class="col-sm-2">Total : <br><?=$prix_total?> €
		</div>
		<input type="hidden" name="panier_item_id" value="<?=$i?>">
	</form>
</div>


		