<div class="row">
	<div class="panier_maj col-md-4 pull-right">
		<div class="wrapper_form_nav">
			<form action="" method="POST" class="user_connect">
				<div class="entete_user_add">
					<p>Votre panier<span class="fermer_panier"> X </span></p>
				
				<!-- </div>
				<?=$nom_produit?>
				<?=$duree?>
				<?=$prix?>
				<?=$reference?> -->

				<form method="post" action="#">
					<table>


						
						<tr>
							<td>Produit</td>
							<td>Durée</td>
							<td>Quantité</td>
							<td>Prix</td>
						</tr>
					
							

					
								<!--echo "<tr>";
									echo "<td>".$_SESSION['panier']['id_produit'][$i]."</ td>";
									echo "<td>".$_SESSION['panier']['duree'][$i]."</td>";
									echo "<td>".$_SESSION['panier']['quantity'][$i]."</td>"; -->
									
						
					</table>
				</form>
				<p>Prix total :</p>
				<button class="payer_panier">Payer</button>
			</form>
		</div>	
	</div>	
</div>