<div class="row">
	<div class="panier_maj col-md-4 pull-right">
		<div class="wrapper_form_nav">
			<form action="" method="POST" class="user_connect">
				<div class="entete_user_add">
					<p>Votre panier<span class="fermer_panier"> X </span></p>
				
				<!-- </div>
				<?=$nom_produit?>
				<?=$duree?>
				<?=$prix?>
				<?=$reference?> -->

				<form method="post" action="#">
					<table>
						<tr>
							<td>Produit</td>
							<td>Durée</td>
							<td>Quantité</td>
							<td>Prix</td>
							<!--<td>Action</td>-->
						</tr>


						<?php
						if (creationPanier())
						{
							$nbArticles=count($_SESSION['panier']['id_produit']);
							if ($nbArticles <= 0)
							echo "<tr><td>Votre panier est vide </ td></tr>";
							else
							{
								for ($i=0 ;$i < $nbArticles ; $i++)
								{
									echo "<tr>";
									echo "<td>".htmlentities($_SESSION['panier']['id_produit'][$i])."</ td>";
									echo "<td>".htmlentities($_SESSION['panier']['duree'][$i])."</td>";
									echo "<td><input type=\"text\" size=\"4\" name=\"quantity[]\" value=\"".htmlentities($_SESSION['panier']['quantity'][$i])."\"/></td>";
									
									echo "<td><a href=\"".htmlentities("/index.php?action=suppression&id_produit=".rawurlencode($_SESSION['panier']['id_produit'][$i]))."\">X</a></td>";
									echo "</tr>";
								}

								// echo "<tr><td colspan=\"2\"> </td>";
								// echo "<td colspan=\"2\">";
								// // echo "Total : ".MontantGlobal();
								// echo "</td></tr>";

								// echo "<tr><td colspan=\"4\">";
								// echo "<input type=\"submit\" value=\"Rafraichir\"/>";
								// echo "<input type=\"hidden\" name=\"action\" value=\"refresh\"/>";

								// echo "</td></tr>";
							}
						}

						$erreur = false;

						$action = (isset($_POST['action'])? $_POST['action']:  (isset($_GET['action'])? $_GET['action']:null )) ;
						if($action !== null){
						   if(!in_array($action,array('ajout', 'suppression', 'refresh'))){
						   	 $erreur=true;
						   }
						  

						   //récuperation des variables en POST ou GET
						   $l = (isset($_POST['l'])? $_POST['l']:  (isset($_GET['l'])? $_GET['l']:null )) ;
						   $p = (isset($_POST['p'])? $_POST['p']:  (isset($_GET['p'])? $_GET['p']:null )) ;
						   $q = (isset($_POST['q'])? $_POST['q']:  (isset($_GET['q'])? $_GET['q']:null )) ;

						   //Suppression des espaces verticaux
						   $l = preg_replace('#\v#', '',$l);
						   //On verifie que $p soit un float
						   $p = floatval($p);

						   //On traite $q qui peut etre un entier simple ou un tableau d'entier
						    
						   if (is_array($q)){
						      $QteArticle = array();
						      $i=0;
						      foreach ($q as $contenu){
						         $QteArticle[$i++] = intval($contenu);
						      }
						   }
						   else
						   $q = intval($q);
						    
						}

						if (!$erreur){
						   switch($action){
						      Case "ajout":
						         ajouterArticle($l,$q,$p);
						         break;

						      Case "suppression":
						         supprimerArticle($l);
						         break;

						      Case "refresh" :
						         for ($i = 0 ; $i < count($QteArticle) ; $i++)
						         {
						            modifierQTeArticle($_SESSION['panier']['libelleProduit'][$i],round($QteArticle[$i]));
						         }
						         break;

						      Default:
						         break;
						   }
						}

						?>
						
					</table>
				</form>
				<p>Prix total :</p>
				<button class="payer_panier">Payer</button>
			</form>
		</div>	
	</div>	
</div>