<div class="header_panier add_panier row">
		<div class="col-sm-2">Référence</div>
		<div class="col-sm-4">Produit</div>
		<div class="col-sm-1">Durée</div>
		<div class="col-sm-1 quant_panier">Quantité</div>
		<div class="col-sm-2">Prix unitaire</div>
		<div class="col-sm-2">Prix total <button class="panier">X</button></div>
</div>
<div class="panier_liste" id="panier_liste">
	<?php require('apps/panier_liste.php');?> 
</div>
