<div class="row">
	<form action="index.php?ajax=panier&edit" class="modif_panier" data-id="<?=$i?>">
		<div class="col-sm-2">
			<a href="index.php?ajax=panier&delete&id_produit=<?=$id_produit?>&duree=<?=$duree?>" class="panier_supp_link">X</a>
			<?=$reference?>
		</div>
		<div class="col-sm-4"><?=$nom_produit?></div>
		<div class="col-sm-1" data-duree="<?=$duree?>" id="mp_duree<?=$i?>"><?=$duree?> min</div>
		<div class="col-sm-1 quant_panier">
			<input type="number" name="quantity" class="quantity" id="mp_quantity<?=$i?>" data-id="<?=$i?>" min="1" value="<?=$quantity?>">
		</div>
		<div class="col-sm-2"><?=$prix?> €</div>
		<div class="col-sm-2"><?=$prix_total?> €</div>
		<input type="hidden" name="panier_item_id" value="<?=$i?>">
		<input type="hidden" name="mp_id_produit" id="mp_id_produit<?=$i?>" value="<?=$id_produit?>">
		<input type="hidden" name="mp_action" id="mp_action<?=$i?>" value="update_panier">
	</form>
</div>


		