<div class="row">
	<div class="col-sm-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium obcaecati eligendi aliquam nostrum, ullam laudantium voluptates facere eaque voluptatibus. Adipisci ratione, eaque odit quisquam velit, quidem consequatur accusantium odio error.</div>
	<div class="col-sm-5"><a href="index.php?page=panier_valid" class="panier">Valider le panier<a></div>
	<div class="col-sm-2">Montant du panier : <?=$prix_total_panier?> €</div>
</div>