<div class="row footer_panier">
	<div class="separator_panier">Montant du panier : </div>
	<div class="mentions_panier col-sm-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium obcaecati eligendi aliquam nostrum, ullam laudantium voluptates facere eaque voluptatibus. Adipisci ratione, eaque odit quisquam velit, quidem consequatur accusantium odio error.</div>
	<div class="col-sm-4"><a href="index.php?page=panier_valid" >Valider le panier</a></div>
	<div class="montant_panier col-sm-3"><?=$prix_total_panier?> €</div>
</div>