<div class="premonitoire">
	<div class="row">
		<img src="./images/premonitoire1.jpg" alt="#"
	class="col-md-2 col-md-offset-5">
	</div>
	<h2>Vous voulez savoir ce que vous prépare l'avenir, avec nos rêves vous serez tout !!</h2>
	<div class="row">
		<img src="./images/premonitoire-amesoeur.jpg" alt="#" class="col-md-2">
		<p class="col-md-8">Si vous voulez tout savoir sur votre futur ame soeur c'est ce rêve qu'il vous faut.</p>
	</div>
	<div class="row">
		<img src="./images/premonitoire-travail.jpg" alt="">		
	</div>
	<div class="row">
		<img src="./images/premonitoire-enfant.jpg" alt=""> 
	</div>













	<img src="index.php?page=produit-single&id_produit=<?=$id_produit?>">
</div>