<form method="POST" action="" class="article" id="addProduit">

		<p>Ajouter un produit</p>
		<label for="title">Nom du produit :</label>
		<input id="title" name="titre" type="text" placeholder="Entrez le nom">
		<label for="description">Description du produit :</label>
		<textarea id="description" name="description"  placeholder="Entrez votre description"></textarea>
		<label for="lien">Lien image du produit :</label>
		<input id="lien" name="lien" type="text" placeholder="La source/lien">
		<input type="hidden" value="addproduit" name="action">
		<button class="creerArticleSend" type="submit">ENVOYER</button>
</form>