<form method="POST" action="" class="produit_add" id="pa">
	<div class="row">
		<div class="entete_user_add">
			<p>Ajouter un produit</p>
		</div>
		<div class="label_input col-md-3">
		<label for="category">Catégorie</label>
		<select name="category" id="category">
			<option value="1">Heureux</option>
			<option value="2">Cauchemar</option>
			<option value="3">Érotique</option>
			<option value="4">Prémonitoire</option>
			<option value="5">Brisé</option>
			<option value="6">Éveillé</option>
			<option value="7">Merdique</option>
		</select>
		</div>
		<div class="label_input col-md-3">
			<label for="nom">Nom :</label>
			<input id="nom" name="nom" type="text" placeholder="Entrez le nom">
		</div>
		<div class="label_input col-md-3 ">
			<label for="reference">Référence :</label>
			<input id="reference" name="reference" type="text" placeholder="Entrez la référence du produit">
		</div>
		<div class="label_input col-md-3">
			<label for="prix">Prix :</label>
			<input id="prix" name="prix" type="text" placeholder="Entrez le prix">
		</div>
		<div class="label_input_ligne col-md-6">
			<label for="description">Description :</label>
			<textarea id="description" name="description"  placeholder="Entrez votre description"></textarea>
		</div>
		<div class="label_input col-md-6">
			<label for="lien0">Lien image :</label>
			<input id="lien0" name="lien0" type="text" placeholder="La source/lien">
			<div class="div_image_add"></div> 	
			<button type="button" id="image_add">Ajouter une autre image</button>
		</div>
		<input type="hidden" value="addproduit" name="action">
		<button class="panier col-md-12" type="submit">AJOUTER</button>
	</div>
</form>