<div class="row">
<form action="index.php?ajax=produit_search_site" method="POST" id="produit_select_site">
	<div class="label-input col-md-12">
		<input class="input_search_site col-md-12"placeholder="Chercher un produit"type="text" name="nom" id="autosearch3" autocomplete="off">
	</div>
	<input type="hidden" id="produit_search">
	<div class="col-md-12" id="result_search_site"></div>
</form>
</div>