<div class="commentaire">
			<button class="add_commentaire">Laissez un commentaire</button>
		<!-- <h3>Commentaires : 
		</h3> -->
		<form id="ps_commentaire" action="index.php?page=produit_single_commentaire_add" method="POST" >
		<div class="mce_hide">
			<textarea name="commentaire" id="ps_comm" cols="30" rows="10" class="mce"></textarea>
		
			<label for="note">Note :</label>
			<select name="note" id="note">
				<option value="5">5</option>
				<option value="4">4</option>
				<option value="3">3</option>
				<option value="2">2</option>
				<option value="1">1</option>
			</select>
			<input type="hidden" name="id_produit" id="ps_id_produit"value="<?=$id_produit?>">
			<input type="hidden" value="commentaire_add" name="action" id="commentaire_add">
			<button type="submit" class="produit_commentaire">Envoyer commentaire</button>

	</form>
</div>