<div class="actualisation_produit">
		<form method="POST" action="" class="produit_add" id="pa">
		<div class="entete_user_add">
			<p>Modifier le produit</p>
		</div>
		<div class="label_input col-md-3">
		<label for="category_modif">Catégorie</label>
		<select name="category" id="category_modif">
			<option value="1">Heureux</option>
			<option value="2">Cauchemar</option>
			<option value="3">Érotique</option>
			<option value="4">Prémonitoire</option>
			<option value="5">Brisé</option>
			<option value="6">Éveillé</option>
			<option value="7">Merdique</option>
		</select>
		</div>
		<div class="label_input col-md-3">
			<label for="nom">Nom :</label>
			<input id="nom" name="nom" type="text" placeholder="Entrez le nom" value="<?=$nom_produit?>">
		</div>
		<div class="label_input col-md-3 ">
			<label for="reference">Référence :</label>
			<input id="reference" value="<?=$reference?>"name="reference" type="text" placeholder="Entrez la référence du produit">
		</div>
		<div class="label_input col-md-3">
			<label for="prix">Prix :</label>
			<input id="prix" value="<?=$prix?>"name="prix" type="text" placeholder="Entrez le prix">
		</div>
		<div class="label_input_ligne col-md-6">
			<label for="description">Description :</label>
			<textarea id="description" name="description"  placeholder="Entrez votre description"><?=$description?></textarea>
		</div>
		<div class="label_input col-md-6">
			<?php require('./apps/produit_modif_img.php');?>
			<div class="div_image_modif"></div> 	
			<button type="button" id="image_modif">Ajouter une autre image</button>
		</div>
		<input type="hidden" value="<?=$id_produit?>" name="id_produit">
		<input type="hidden" value="produit_modif_submit" name="action">
		<button class="panier col-md-12" type="submit">MODIFIER</button>
</form>
</div>