	<div class="row">
		<form action="index.php?ajax=produit_search" method="POST" class="produit_add" id="produit_select">
			<div class="entete_user_add">
				<p>Selectionner le produit à modifier</p>
			</div>
			<div class="label-input col-md-6">
				<label for="category">Catégorie</label>
				<select name="category" id="category">
					<option value="1">Heureux</option>
					<option value="2">Cauchemar</option>
					<option value="3">Érotique</option>
					<option value="4">Prémonitoire</option>
					<option value="5">Brisé</option>
					<option value="6">Éveillé</option>
					<option value="7">Merdique</option>
				</select>
			</div>
			<div class="label-input col-md-6">
				<label for="autosearch">Chercher le produit</label>
				<input type="text" name="nom" id="autosearch">
			</div>
			<input type="hidden" id="produit_search">
			<div class="col-md-12" id="result_search"></div>
		</form>
		
</div>