<div class="row">
	<div class="connection col-md-12">
		<div class="wrapper_form_nav">
			<form action="index.php?page=login" method="POST" class="user_connect">
				<div class="entete_user_add">
					<p>Se connecter <span class="fermer_add_user"> X </span></p>
				</div>
				<div class="label_input">
					<label for="email">E-mail :</label>
					<input id="email" type="text" name="email" required>
				</div>
				<div class="label_input">
					<label for="mdp" >Mot de passe :</label>
					<input type="password" id="mdp" name="pass" required>
				</div>
				<div class="label_input">
					<button class="creer_compte">Connexion</button>
					<a href="">[ mot de passe oublié ? ]</a>
				</div>
			</form>
		</div>	
	</div>	
</div>