<div class="modif_user">
	<form action="index.php?ajax=user_modif&id_user=<?=$user->getId();?>" id="form_user_modif" method="POST">
		<p>
			<label class="infos">Nom : </label>
			<input type="text" id="um_nom" name="nom" value="<?=htmlentities($user->getNom());?>">
		</p>
		<p>
			<label class="infos">Prénom : </label>
			<input type="text" id="um_prenom" name="prenom" value="<?=htmlentities($user->getPrenom());?>">
		</p>
		<p>
			<label class="infos">Date de naissance : </label>
			<input type="text" disabled value="<?=$user->getBirthday();?>">
		</p>
		<p>
			<label class="infos">Téléphone : </label>
			<input type="text" id="um_telephone" name="telephone" value="<?=htmlentities($user->getTelephone());?>">
		</p>
		<p>
			<label class="infos">Email : </label>
			<input type="text" id="um_email" name="email" value="<?=htmlentities($user->getEmail());?>">
		</p>
			<input type="hidden" name="action" id="um_action" value="user_modif">
		<button class="creer_compte">Modifier</button>
	</form>
</div>