<div class="user_single col-md-6">
	<h3>Votre compte</h3>
	<div class="row">
		<div class="col-sm-6">
			<p><span class="infos">Nom : </span><br><?=$nom?></p>
			<p><span class="infos">Prenom : </span><br><?=$prenom?></p>
			<p><span class="infos">Date de naissance : </span><br><?=$date_naissance?></p>
			<p><span class="infos">Téléphone : </span><br><?=$telephone?></p>
			<p><span class="infos">Email : </span><br><?=$email?></p>
		</div>
		<div class="user_commande_liste col-sm-6">
			<h3>Vos commandes</h3>
			<?php require('apps/user_commande_liste.php') ;?>
		</div>
	</div>
	<div class="user_adresse row">
		<h3>Vos adresses</h3>
		<?php require('apps/user_adresse.php') ?>
	</div>
</div>

		