<div class="row">
	<div class="connection col-md-12">	
		<form action="index.php?page=login" method="POST" class="log">
			<div class="entete_user_add">
				<p>Se connecter</p>
				<div class="fermer"> X </div>
			</div>
			<div class="entete_user_add">
				<label for="email">E-mail :</label>
				<input id="email" type="text" name="email" required>
			</div>
			<div class="entete_user_add">
				<label for="mdp" >Mot de passe :</label>
				<input type="password" id="mdp" name="pass" required>
			</div>
			<div class="entete_user_add">
				<a href="">[ mot de passe oublié ? ]</a>
				<button>Connexion</button>
			</div>
		</form>
	</div>
</div>