<div class="design_adresse">
	<form action="index.php?ajax=user_adresse_add&id_user=<?=$user->getId();?>" id="form_adresse_add" method="POST">

		<p>
			<label class="infos">Nom : </label>
			<input type="text" class="add_nom_adresse" name="nom_adresse" >
		</p>
		<p>
			<label class="infos">Prénom : </label>
			<input type="text" class="add_prenom_adresse" name="prenom_adresse">
		</p>
		<p>
			<label class="infos">Adresse : </label>
			<input type="text" class="add_ligne1" name="ligne1">
			<input type="text" class="add_ligne2" name="ligne2">
		</p>
		
		<p>
			<label class="infos">Code : </label>
			<input type="text" class="add_code" name="code">
		</p>
		<p>
			<label class="infos">Ville : </label>
			<input type="text" class="add_ville" name="ville">
		</p>
		<p>
			<label class="infos">Pays : </label>
			<input type="text" class="add_pays" name="pays">
		</p>
			<input type="hidden" name="action" value="user_adresse_add" class="add_action">

		<button class="creer_compte">Modifier</button>		
	</form>
</div>		