<div class="row">
<div class="inscription col-md-12">
	<form action="" method="POST" class="user_add ">
		<div class="entete_user_add">
			<p>Créez votre espace personnel <span class="fermer_add_user">X</span></p>
			
		</div>
		<div class="label_input">
			<label for="username">Nom :</label>
			<input id="username" type="text" name="nom" required>
		</div>
		<div class="label_input">
			<label for="username">Prénom :</label>
			<input id="username" type="text" name="prenom" required>
		</div>
		<div class="label_input">
			<label for="email">Adresse email :</label>
			<input id="email" type="email" name="email" required>
		</div>
		<div class="label_input">
			<label for="telephone">Numéro de téléphone :</label>
			<input id="telephone" type="telephone" name="telephone" required>
		</div>
		<div class="label_input">
			<label for="date">Date de naissance :</label>
			<input id="date" name="date_naissance" placeholder="aaaa-mm-jj" maxlength="10" required>
		</div>
		<div class="label_input">
			<label for="mdp">Mot de passe :</label>
			<input id="mdp" type="password" name="password" required>
		</div>
		<div class="label_input">
			<label for="mdpconf">Confirmer le mot de passe :</label>
			<input id="mdpconf" type="password" name="password2" required>
		</div>
			<input type="hidden" name="action" value="register">
		<button class="creer_compte">Créer</button>
	</form>
</div>
</div>
