<div class="row">
	<div class="inscription col-md-12">
		<div id="ua_message"></div>
		<div class="wrapper_form_nav">
			<form action="index.php?ajax=user_add" method="POST" class="user_add" id="user_add">
				<div class="entete_user_add">
					<p>Créez votre espace personnel <span class="fermer_add_user">X</span></p>
				</div>
				<div class="label_input">
					<label for="ua_name">Nom :</label>
					<input id="ua_name" type="text" name="nom" required>
				</div>
				<div class="label_input">
					<label for="ua_username">Prénom :</label>
					<input id="ua_username" type="text" name="prenom" required>
				</div>
				<div class="label_input">
					<label for="ua_email">Adresse email :</label>
					<input id="ua_email" type="email" name="email" required>
				</div>
				<div class="label_input">
					<label for="ua_telephone">Numéro de téléphone :</label>
					<input id="ua_telephone" type="telephone" name="telephone" required>
				</div>
				<div class="label_input">
					<label for="ua_date">Date de naissance :</label>
					<input id="ua_date" name="date_naissance" placeholder="aaaa-mm-jj" maxlength="10" required>
				</div>
				<div class="label_input">
					<label for="ua_password">Mot de passe :</label>
					<input id="ua_password" type="password" name="password" required>
				</div>
				<div class="label_input">
					<label for="ua_password2">Confirmez :</label>
					<input id="ua_password2" type="password" name="password2" required>
				</div>
					<input type="hidden" name="action" id="ua_action" value="register">
				<button class="creer_compte">Créer</button>
			</form>
		</div>
	</div>
</div>
