<div class="row">

	<div class="connection col-md-12">
		<div id="uc_message"></div>
		<h3 id="ua_ok">Inscription réussie, connectez-vous !</h3>
		<div class="wrapper_form_nav">
			<form id="uc" action="index.php?ajax=login" method="POST" class="user_connect">
				<div class="entete_user_add">
					<p>Se connecter <span class="fermer_connect"> X </span></p>
				</div>
				<div class="label_input">
					<label for="uc_email">E-mail :</label>
					<input id="uc_email" type="text" name="email" required>
				</div>
				<div class="label_input">
					<label for="uc_password" >Mot de passe :</label>
					<input type="password" id="uc_password" name="pass" required>
				</div>
				<div class="label_input">
				</div>
					<button class="creer_compte">Connexion</button>
					<input type="hidden" name="action" value="connect" id="uc_connect">
					<a href="" class="mdp_oubli">[ mot de passe oublié ? ]</a>
			</form>
		</div>	
	</div>	
</div>