<div class="col-md-12">
	<div class="row">	
		<div class="user_single col-md-6">
			<h3>Votre compte</h3>
				<a id="modif_user_link" data-id="<?=$user->getId();?>" href="index.php?ajax=user_modif">Modifier mes informations</a>
			<div id="modif_user">
				<?php require('apps/user_single.php') ?>
			</div>
		</div>
		<div class="user_commande_liste col-sm-6">
			<h3>Vos commandes</h3>
			<div class="row">
				<div class="col-sm-2">Numéro commande</div>
				<div class="col-sm-2">Numéro facture</div>
				<div class="col-sm-4">Date commande</div>
				<div class="col-sm-2">Prix total</div>
				<div class="col-sm-2">Statut</div>
			</div>

			<?php require('apps/user_commande_liste.php') ;?>
		</div>
	</div>
</div>
<div class="col-md-12">
	<div class="user_adresse row">
		<h3>Vos adresses</h3><a data-user="<?=$user->getId();?>" id="add_adresse" href="index.php?ajax=user_adresse_add">Ajouter une adresse</a>
		<div id="modif_adresse">
			<?php require('apps/user_adresse.php') ?>
		</div>
	</div>
</div>


		