<div class="col-sm-3 design_adresse" id="modif_adresse<?=$id_adresse?>">
	<a data-id="<?=$id_adresse?>" data-user="<?=$id_user?>" href="index.php?ajax=user_adresse_modif" class="modif_adresse_link">Modifier cette adresse</a>
	<p><span class="infos">Nom : </span><br><?=$nom_adresse?></p>
	<p><span class="infos">Prénom : </span><br><?=$prenom_adresse?></p>
	<p><span class="infos">Adresse : </span><br><?=$ligne1?><br><?=$ligne2?></p>
	<p><span class="infos">Code postal : </span><br><?=$code?></p>
	<p><span class="infos">Ville : </span><br><?=$ville?></p>
</div>
