<form action="index.php?ajax=user_adresse_modif&id_user=<?=$user->getId();?>&id_adresse=<?=$id_adresse?>" id="form_adresse_modif<?=$id_adresse?>" method="POST">

	<p><label class="infos">Nom : </label>
		<input type="text" class="am_nom_adresse" name="nom_adresse" value="<?=$nom_adresse?>"></p>
	<p><label class="infos">Prénom : </label>
		<input type="text" class="am_prenom_adresse" name="prenom_adresse" value="<?=$prenom_adresse?>"></p>
	<p><label class="infos">Adresse : </label>
		<input type="text" class="am_ligne1" name="ligne1" value="<?=$ligne1?>">
	<input type="text" class="am_ligne2" name="ligne2" value="<?=$ligne2?>"></p>
	
	<p><label class="infos">Code : </label>
		<input type="text" class="am_code" name="code" value="<?=$code?>"></p>
	<p><label class="infos">Ville : </label>
		<input type="text" class="am_ville" name="ville" value="<?=$ville?>"></p>
	<p><label class="infos">Pays : </label>
		<input type="text" class="am_pays" name="pays" value="<?=$pays?>"></p>
		<input type="hidden" name="action" value="user_adresse_modif<?=$id_adresse?>" class="am_action">

<button class="creer_compte">Modifier</button>
				
			
</form>
		


		